**Week 1 (1. Hafta)**

Burada Matlab Komut satırlarına veya M file'a yazılan kodları ve çıktıları kaydetmek için Jupyter Notebook dosyasını seçtim. Bunun PDF'e📁 çevrilmiş halini de görebilirsiniz😊

Bu ders notunu Matlab'ı sevdiğimden dolayı çıkartıyorum. Umarım hoşunuza gider. Vize ve Final sınavlarınızda🗒🖊 başarılar dilerim😁😄

short formata göre 4 digit var

In [12]:
a = 4

pi 


a =

     4


ans =

    3.1416




noktanın öncesi ve sonrası dahil 7 digit vardır

In [7]:
digits(7)
pi


ans =

    3.1416




digit komutundan sonra vpa yardımcısı ile kullanılarak elde edersin

In [8]:
vpa(pi) 

 
ans =
 
3.141593
 



bu da 2. yol "sym" ile

In [10]:
sym(pi,'d')

 
ans =
 
3.141593
 



digit komutunu kullanmadan vpa ile pi değer girildikten sonra istenilen digite gönderme

In [11]:
vpa(pi,3) 

 
ans =
 
3.14
 



z = 2 + 3j

matlab''da "j" karakter de "i" karakter de kullanılır ancak matlab karşılığı "i" ile verir 

In [13]:
z = 2 + 3j


z =

   2.0000 + 3.0000i




**Week 2 (2. Hafta)**

In [16]:
[theta  r] = cart2pol(real(z),imag(z))


theta =

    0.9828


r =

    3.6056




In [14]:
[a b] = cart2pol(53.1401*pi/5,5)


a =

    0.1486


b =

   33.7612




In [17]:
[a b] = cart2pol(theta,r)


a =

    1.3047


b =

    3.7371




In [15]:
x = [1 2 3 4 5]

f = 2*x + 4 

f2 = 2*x.^2 + 4


x =

     1     2     3     4     5


f =

     6     8    10    12    14


f2 =

     6    12    22    36    54




f(t) = A sin(wt)  t = 0:10  


% increment value(artış değer) => 1  


t = 0:0.5:10  


% increment value(artış değer) => 0.5

**NOT** : Artış değer rastgele tanımlanmamalıdır. Mesela t = 0 ... 9.7 ile bitebilir. 

Bu sorundan kurtulmak için:
t = initial value : <sup>final value - initial value</sup>&frasl;<sub>number of gaps</sub> : final value

$$t = linspace(inital value, final value)
% Toplam 100 elemandan diziyi oluşturur

t = linspace(0,10,500)


% sonucu göstermez matlab'da ancak Jupyter Notebook'ta gösterir😄😂 yani 500 tane sayıdan oluşan dizi(ondan emin değilim ama ne demek istediğimi anladınız😅) olur. Neyse grafiksel çizidrmek istersek default modda mavi çizgi ile çizilir.

fliplr

flipud

-> satırdaki sayıları ters çevirir

In [18]:
A = [1 2 3; 4 5 6]


A =

     1     2     3
     4     5     6




In [19]:
fliplr(A)


ans =

     3     2     1
     6     5     4




In [20]:
B = rot90(A)


B =

     3     6
     2     5
     1     4




In [21]:
C = rot90(A,2)


C =

     6     5     4
     3     2     1




In [22]:
D = repmat(A,2)


D =

     1     2     3     1     2     3
     4     5     6     4     5     6
     1     2     3     1     2     3
     4     5     6     4     5     6




In [23]:
E = repmat(A,2,3)


E =

     1     2     3     1     2     3     1     2     3
     4     5     6     4     5     6     4     5     6
     1     2     3     1     2     3     1     2     3
     4     5     6     4     5     6     4     5     6




In [24]:
size(A)


ans =

     2     3




In [25]:
length(A)


ans =

     3




Matrix' in elaman sayısını verir 

In [26]:
numel(A)


ans =

     6




**NOT** : Tek satır veya tek sütun matrix yapılarında length ve numel aynı değeri verir

w = logspace(-1,2)

50 tane tanımlar

tabanlar eşittir üsler yazılır

w = logspace(-1,2,200)

200 tane elemandan oluşur

Birim Matris

In [ ]:
eye


ans =

     1




In [39]:
eye(3)


ans =

     1     0     0
     0     1     0
     0     0     1




Elemanı birlerden oluşur

In [28]:
ones


ans =

     1




In [38]:
ones(3)


ans =

     1     1     1
     1     1     1
     1     1     1




Elemanı sıfırlardan oluşur

In [35]:
zeros


ans =

     0




In [36]:
zeros(2,3)


ans =

     0     0     0
     0     0     0




In [37]:
zeros(2)


ans =

     0     0
     0     0




In [33]:
diag

Not enough input arguments.



In [29]:
diag(2)


ans =

     2




In [31]:
diag(2,3)


ans =

     0     0     0     2
     0     0     0     0
     0     0     0     0
     0     0     0     0




In [32]:
diag(2,3,4)

Too many input arguments.



In [34]:
diag(0,4)


ans =

     0     0     0     0     0
     0     0     0     0     0
     0     0     0     0     0
     0     0     0     0     0
     0     0     0     0     0




In [40]:
diag([1 2 3])


ans =

     1     0     0
     0     2     0
     0     0     3




Çaprazlarda sağda ve solda toplamları eşit olan bir matris verir

In [41]:
magic(3)


ans =

     8     1     6
     3     5     7
     4     9     2




Hatta görelim

In [49]:
sum(magic(3))


ans =

    15    15    15




0 ile 1 aralığında rastgele sayı üretir

In [42]:
rand


ans =

    0.8147




Negatif değerleri de kapsayan bir sayı üretir

In [43]:
randn


ans =

    1.8339




3'e kadar rastgele sayı üretir

In [45]:
randi(3)


ans =

     1




randi(üretilecek en büyük değer, kare matrix'in satır-sütun sayısı)

In [48]:
randi(3,2)


ans =

     3     1
     2     1




In [51]:
perms([1 2 3])


ans =

     3     2     1
     3     1     2
     2     3     1
     2     1     3
     1     3     2
     1     2     3




Sayı değeri tam sayı olmak kaydı ile rastgele tam sayıları dizmek için kullanılır

In [52]:
P = perms([1 2 3; 4 5 6])


P =

     6     3     5     2     4     1
     6     3     5     2     1     4
     6     3     5     4     2     1
     6     3     5     4     1     2
     6     3     5     1     2     4
     6     3     5     1     4     2
     6     3     2     5     4     1
     6     3     2     5     1     4
     6     3     2     4     5     1
     6     3     2     4     1     5
     6     3     2     1     5     4
     6     3     2     1     4     5
     6     3     4     5     2     1
     6     3     4     5     1     2
     6     3     4     2     5     1
     6     3     4     2     1     5
     6     3     4     1     5     2
     6     3     4     1     2     5
     6     3     1     5     2     4
     6     3     1     5     4     2
     6     3     1     2     5     4
     6     3     1     2     4     5
     6     3     1     4     5     2
     6     3     1     4     2     5
     6     5     3     2     4     1
     6     5     3     2     1     4
     6     5     3     4     2  

In [53]:
size(P)


ans =

   720     6




randperm(maximum sayı, sayı miktarı)

In [54]:
randperm(4,2)


ans =

     4     2




In [55]:
sum([1 3 4])


ans =

     8




In [56]:
sum([1; 3; 4])


ans =

     8




In [57]:
A = [1 3 5; 2 4 6]


A =

     1     3     5
     2     4     6




In [58]:
sum(A)


ans =

     3     7    11




In [59]:
sort(A)


ans =

     1     3     5
     2     4     6




In [60]:
sort([-2 10 0 6])


ans =

    -2     0     6    10




In [61]:
max(A)


ans =

     2     4     6




In [62]:
min(A)


ans =

     1     3     5




In [64]:
C = [1 2 3]
sum(C)/numel(C)


C =

     1     2     3


ans =

     2




In [65]:
rank(C)


ans =

     1




In [66]:
rank(A)


ans =

     2




In [67]:
rank(B)


ans =

     2


