***Çalışma Soruları

1. Soru


In [1]:
A = [2 4 7 35+3j 5*exp(-1.6) sqrt(23) sin(pi/2)]


A =

   2.0000 + 0.0000i   4.0000 + 0.0000i   7.0000 + 0.0000i  35.0000 + 3.0000i   1.0095 + 0.0000i   4.7958 + 0.0000i   1.0000 + 0.0000i




2. Soru


In [2]:
A = [1:10]


A =

     1     2     3     4     5     6     7     8     9    10




In [3]:
A = [1:2:10]


A =

     1     3     5     7     9




In [4]:
A = [2:2:10]


A =

     2     4     6     8    10




3. Soru

In [5]:
A = [1:0.5:10]


A =

  Columns 1 through 13

    1.0000    1.5000    2.0000    2.5000    3.0000    3.5000    4.0000    4.5000    5.0000    5.5000    6.0000    6.5000    7.0000

  Columns 14 through 19

    7.5000    8.0000    8.5000    9.0000    9.5000   10.0000




In [7]:
A = [5:-0.25:1]


A =

  Columns 1 through 13

    5.0000    4.7500    4.5000    4.2500    4.0000    3.7500    3.5000    3.2500    3.0000    2.7500    2.5000    2.2500    2.0000

  Columns 14 through 17

    1.7500    1.5000    1.2500    1.0000




In [8]:
A = linspace(0, 20, 120)


A =

  Columns 1 through 13

         0    0.1681    0.3361    0.5042    0.6723    0.8403    1.0084    1.1765    1.3445    1.5126    1.6807    1.8487    2.0168

  Columns 14 through 26

    2.1849    2.3529    2.5210    2.6891    2.8571    3.0252    3.1933    3.3613    3.5294    3.6975    3.8655    4.0336    4.2017

  Columns 27 through 39

    4.3697    4.5378    4.7059    4.8739    5.0420    5.2101    5.3782    5.5462    5.7143    5.8824    6.0504    6.2185    6.3866

  Columns 40 through 52

    6.5546    6.7227    6.8908    7.0588    7.2269    7.3950    7.5630    7.7311    7.8992    8.0672    8.2353    8.4034    8.5714

  Columns 53 through 65

    8.7395    8.9076    9.0756    9.2437    9.4118    9.5798    9.7479    9.9160   10.0840   10.2521   10.4202   10.5882   10.7563

  Columns 66 through 78

   10.9244   11.0924   11.2605   11.4286   11.5966   11.7647   11.9328   12.1008   12.2689   12.4370   12.6050   12.7731   12.9412

  Columns 79 through 91

   13.1092   13.2773   13.44

In [11]:
format long
A = logspace(1, 10000, 150)


A =

  1.0e+269 *

  Columns 1 through 6

   0.000000000000000   0.000000000000000   0.000000000000000   0.000000000000000   2.688624806652982                 Inf

  Columns 7 through 12

                 Inf                 Inf                 Inf                 Inf                 Inf                 Inf

  Columns 13 through 18

                 Inf                 Inf                 Inf                 Inf                 Inf                 Inf

  Columns 19 through 24

                 Inf                 Inf                 Inf                 Inf                 Inf                 Inf

  Columns 25 through 30

                 Inf                 Inf                 Inf                 Inf                 Inf                 Inf

  Columns 31 through 36

                 Inf                 Inf                 Inf                 Inf                 Inf                 Inf

  Columns 37 through 42

                 Inf                 Inf                 Inf                

4. soru

In [12]:
format short

In [13]:
zeros(3,4)


ans =

     0     0     0     0
     0     0     0     0
     0     0     0     0




In [14]:
ones(3)
% ones(3,3)


ans =

     1     1     1
     1     1     1
     1     1     1




In [15]:
diag([1 2 3 4])


ans =

     1     0     0     0
     0     2     0     0
     0     0     3     0
     0     0     0     4




In [16]:
10*rand(3) + 10


ans =

   18.1472   19.1338   12.7850
   19.0579   16.3236   15.4688
   11.2699   10.9754   19.5751




5. Soru

In [20]:
A = [0:3:24]
B = A.' %Transpose Matrix


A =

     0     3     6     9    12    15    18    21    24


B =

     0
     3
     6
     9
    12
    15
    18
    21
    24




6. Soru

In [24]:
A = [linspace(0, 20, 6); linspace(17, 12, 6); linspace(1.1, -0.4, 6)]


A =

         0    4.0000    8.0000   12.0000   16.0000   20.0000
   17.0000   16.0000   15.0000   14.0000   13.0000   12.0000
    1.1000    0.8000    0.5000    0.2000   -0.1000   -0.4000




7. Soru

In [25]:
A = [linspace(1,13,5); linspace(2,14,5); linspace(3,15,5)]


A =

     1     4     7    10    13
     2     5     8    11    14
     3     6     9    12    15




In [26]:
B = A(2,:)


B =

     2     5     8    11    14




In [28]:
C = A(:,[1,4])


C =

     1    10
     2    11
     3    12




8. Soru

In [34]:
A = [linspace(2, 57, 12)]'
B = A([1,2,9,10,11,12],:)'


A =

     2
     7
    12
    17
    22
    27
    32
    37
    42
    47
    52
    57


B =

     2     7    42    47    52    57




9. Soru

In [39]:
format short
A = [linspace(11, 1, 6); linspace(-2,0,6); linspace(0,-5,6); 8 6 4 2 4 6]


A =

   11.0000    9.0000    7.0000    5.0000    3.0000    1.0000
   -2.0000   -1.6000   -1.2000   -0.8000   -0.4000         0
         0   -1.0000   -2.0000   -3.0000   -4.0000   -5.0000
    8.0000    6.0000    4.0000    2.0000    4.0000    6.0000




In [40]:
B = A ([1,4],[3,4])


B =

     7     5
     4     2




In [41]:
C = A(:,[1,3:5])


C =

   11.0000    7.0000    5.0000    3.0000
   -2.0000   -1.2000   -0.8000   -0.4000
         0   -2.0000   -3.0000   -4.0000
    8.0000    4.0000    2.0000    4.0000




In [42]:
D = A([1,2],:)


D =

   11.0000    9.0000    7.0000    5.0000    3.0000    1.0000
   -2.0000   -1.6000   -1.2000   -0.8000   -0.4000         0




10. Soru

In [50]:
A = eye(5) 
A([4,5],3) = 1
A


A =

     1     0     0     0     0
     0     1     0     0     0
     0     0     1     0     0
     0     0     0     1     0
     0     0     0     0     1


A =

     1     0     0     0     0
     0     1     0     0     0
     0     0     1     0     0
     0     0     1     1     0
     0     0     1     0     1


A =

     1     0     0     0     0
     0     1     0     0     0
     0     0     1     0     0
     0     0     1     1     0
     0     0     1     0     1




In [51]:
A([3,4,5],[1,2]) = 3


A =

     1     0     0     0     0
     0     1     0     0     0
     3     3     1     0     0
     3     3     1     1     0
     3     3     1     0     1




In [52]:
A([1,2],[3,4,5]) = 2


A =

     1     0     2     2     2
     0     1     2     2     2
     3     3     1     0     0
     3     3     1     1     0
     3     3     1     0     1


